=== anddrenunes/SemanticMedWeb/instance-gen/ccd-ca92a9c1-275f-42ca-b1a0-ac0a20cb2ec9.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
  xmlns:mlhim2="http://www.mlhim.org/xmlns/mlhim2/2_4_1"
  xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"
  xmlns:dc= "http://purl.org/dc/elements/1.1/"
  elementFormDefault="qualified"
  targetNamespace="http://www.mlhim.org/xmlns/mlhim2/2_4_1"
  xmlns:data-view="http://www.w3.org/2003/g/data-view#"
  data-view:transformation="http://www.mlhim.org/ccd/ccd_md_view.xsl">
  
  <xs:annotation>
    <xs:appinfo>

      <rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#" xmlns:dc= "http://purl.org/dc/elements/1.1/">

	<rdf:Description rdf:about="http://www.hkcr.net/ccd/ccd-ca92a9c1-275f-42ca-b1a0-ac0a20cb2ec9">
	  <dc:title>Demographics for MLHIM Test Framework</dc:title>
	  <dc:creator>Timothy W. Cook &lt;timothywayne.cook@gmail.com&gt; </dc:creator>
          <dc:contributor>None</dc:contributor>
          <dc:subject>Demographics; ccd2data, ccd_file</dc:subject>
	  <dc:source>MLHIM Test Suite</dc:source>
	  <dc:rights>CC-BY http://creativecommons.org/licenses/by/3.0/</dc:rights>
	  <dc:relation>None</dc:relation>
	  <dc:coverage>Universal</dc:coverage>
	  <dc:type>MLHIM Concept Constraint Definition (CCD)</dc:type>
	  <dc:identifier>ccd-ca92a9c1-275f-42ca-b1a0-ac0a20cb2ec9</dc:identifier>
	  <dc:description>CCD to model a simple set of demographic entries to create data for test scenarios.  
	  	This CCD is to be used with ccd2data.py It does not represent best practice in CCD design.</dc:description>
	  <dc:publisher>MLHIM</dc:publisher>
	  <dc:date>2012-10-21</dc:date>
	  <dc:format>text/xml</dc:format>
	  <dc:language>en-US</dc:language>
	</rdf:Description>
      </rdf:RDF>
    </xs:appinfo>
  </xs:annotation>

  <xs:include schemaLocation="http://www.mlhim.org/xmlns/mlhim2/2_4_1/mlhim2.xsd"/>

  <xs:element name="ccd-ca92a9c1-275f-42ca-b1a0-ac0a20cb2ec9" type="mlhim2:ct-4e2099ab-e928-4b66-8d08-fb006b780b10"/>
  <xs:complexType name="ct-4e2099ab-e928-4b66-8d08-fb006b780b10">
    <xs:complexContent>
    <xs:restriction base="mlhim2:CCDType">
	<xs:sequence>
		<xs:element minOccurs="1"  maxOccurs="1" ref="mlhim2:el-249daa52-7cdc-44bb-8cd8-7071993de08b"/>
	</xs:sequence>
    </xs:restriction>
    </xs:complexContent>
  </xs:complexType>
  <xs:element name="el-249daa52-7cdc-44bb-8cd8-7071993de08b" substitutionGroup="mlhim2:definition" type="mlhim2:ct-249daa52-7cdc-44bb-8cd8-7071993de08b"/>
	
	<xs:complexType name='ct-249daa52-7cdc-44bb-8cd8-7071993de08b'>
		<xs:complexContent>
			<xs:restriction base='mlhim2:ClusterType'>
				<xs:sequence>
					<xs:element maxOccurs='unbounded' minOccurs='0' ref='mlhim2:links'/>
					<xs:element maxOccurs='1' minOccurs='0' ref='mlhim2:feeder-audit'/>
					<xs:element maxOccurs='1' minOccurs='1' name='cluster-subject' type='xs:string' fixed='Demographics Cluster'/>
					<xs:element maxOccurs='1' minOccurs='1' ref='mlhim2:el-a2bc25db-3111-4cd5-9825-d9c448cdd1a5'/>
				</xs:sequence>
			</xs:restriction>
		</xs:complexContent>
	</xs:complexType>
	<xs:element name='el-a2bc25db-3111-4cd5-9825-d9c448cdd1a5' substitutionGroup='mlhim2:items' type='mlhim2:ct-a2bc25db-3111-4cd5-9825-d9c448cdd1a5'/>
	
	<!-- Cluster Items List - Additional ItemType subtypes may be added here.-->
	<xs:complexType name='ct-a2bc25db-3111-4cd5-9825-d9c448cdd1a5'>
		<xs:complexContent>
			<xs:extension base='mlhim2:ItemType'>
				<xs:sequence>
					<xs:element maxOccurs='1' minOccurs='1' ref='mlhim2:el-7562af32-6e33-4a21-ab84-e9067331c465'/>
					<xs:element maxOccurs='1' minOccurs='1' ref='mlhim2:el-a35f0879-4338-4908-a36f-ce16fc67cf7a'/>
					<xs:element maxOccurs='1' minOccurs='1' ref='mlhim2:el-b291c9b2-f0ec-4ec2-9bed-5fac28afbd32'/>
					<xs:element maxOccurs='1' minOccurs='1' ref='mlhim2:el-018c1d4e-d8e5-4537-b564-45191d5577bd'/>										
					<xs:element maxOccurs='1' minOccurs='1' ref='mlhim2:el-88d991a4-aa08-4767-aaab-fbf4197d5bd7'/>										
					<xs:element maxOccurs='1' minOccurs='1' ref='mlhim2:el-09952004-eed1-4ba7-be91-340bc24af7c3'/>										
					<xs:element maxOccurs='1' minOccurs='1' ref='mlhim2:el-0b9a525a-fdc8-40f3-abd8-a83a993d418c'/>										
					<xs:element maxOccurs='1' minOccurs='1' ref='mlhim2:el-ef538f44-e84b-455e-8db5-2ef40ef40b5e'/>										
					<xs:element maxOccurs='1' minOccurs='1' ref='mlhim2:el-b380e079-af34-430d-88b4-599087fcdec4'/>										
					<xs:element maxOccurs='1' minOccurs='1' ref='mlhim2:el-06b0c425-f7ef-4d46-8573-97091ae52d60'/>										
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:element name='el-7562af32-6e33-4a21-ab84-e9067331c465' substitutionGroup='mlhim2:Item' type='mlhim2:ct-7562af32-6e33-4a21-ab84-e9067331c465'/>
	<xs:element name='el-a35f0879-4338-4908-a36f-ce16fc67cf7a' substitutionGroup='mlhim2:Item' type='mlhim2:ct-a35f0879-4338-4908-a36f-ce16fc67cf7a'/>	
	<xs:element name='el-b291c9b2-f0ec-4ec2-9bed-5fac28afbd32' substitutionGroup='mlhim2:Item' type='mlhim2:ct-b291c9b2-f0ec-4ec2-9bed-5fac28afbd32'/>	
	<xs:element name='el-018c1d4e-d8e5-4537-b564-45191d5577bd' substitutionGroup='mlhim2:Item' type='mlhim2:ct-018c1d4e-d8e5-4537-b564-45191d5577bd'/>	
	<xs:element name='el-88d991a4-aa08-4767-aaab-fbf4197d5bd7' substitutionGroup='mlhim2:Item' type='mlhim2:ct-88d991a4-aa08-4767-aaab-fbf4197d5bd7'/>	
	<xs:element name='el-09952004-eed1-4ba7-be91-340bc24af7c3' substitutionGroup='mlhim2:Item' type='mlhim2:ct-09952004-eed1-4ba7-be91-340bc24af7c3'/>	
	<xs:element name='el-0b9a525a-fdc8-40f3-abd8-a83a993d418c' substitutionGroup='mlhim2:Item' type='mlhim2:ct-0b9a525a-fdc8-40f3-abd8-a83a993d418c'/>	
	<xs:element name='el-ef538f44-e84b-455e-8db5-2ef40ef40b5e' substitutionGroup='mlhim2:Item' type='mlhim2:ct-ef538f44-e84b-455e-8db5-2ef40ef40b5e'/>	
	<xs:element name='el-b380e079-af34-430d-88b4-599087fcdec4' substitutionGroup='mlhim2:Item' type='mlhim2:ct-b380e079-af34-430d-88b4-599087fcdec4'/>	
	<xs:element name='el-06b0c425-f7ef-4d46-8573-97091ae52d60' substitutionGroup='mlhim2:Item' type='mlhim2:ct-06b0c425-f7ef-4d46-8573-97091ae52d60'/>	
	
	<!--Gender-->
	<xs:complexType name='ct-06b0c425-f7ef-4d46-8573-97091ae52d60'>
		<xs:complexContent>
			<xs:restriction base='mlhim2:ElementType'>
				<xs:sequence>
					<xs:element  maxOccurs='1' minOccurs='1' ref='mlhim2:el-0ac3f22e-64ca-4309-be88-874cd14649a0'/>
				</xs:sequence>
			</xs:restriction>
		</xs:complexContent>
	</xs:complexType>
	<xs:element name='el-0ac3f22e-64ca-4309-be88-874cd14649a0' substitutionGroup='mlhim2:Element-dv' type='mlhim2:ct-0ac3f22e-64ca-4309-be88-874cd14649a0'/>
	
	
	<xs:complexType name='ct-0ac3f22e-64ca-4309-be88-874cd14649a0'>
		<xs:complexContent>
			<xs:restriction base='mlhim2:DvStringType'>
				<xs:sequence>
					<xs:element maxOccurs='1' minOccurs='1' name='data-name' type='xs:string' fixed='Gender'/>
					<xs:element maxOccurs='1' minOccurs='0' ref='mlhim2:ExceptionalValue'/>
					<xs:element maxOccurs='1' minOccurs='0' name='valid-time-begin' type='xs:dateTime'/>
					<xs:element maxOccurs='1' minOccurs='0' name='valid-time-end' type='xs:dateTime'/>
				  <xs:element maxOccurs='1' minOccurs='1' name='DvString-dv' type='xs:string' rdf:resource="http://purl.bioontology.org/ontology/SNOMEDCT/152323006">
						<xs:annotation>
							<xs:documentation>
								Gender
							</xs:documentation>
						</xs:annotation>
					</xs:element>
				</xs:sequence>
			</xs:restriction>
		</xs:complexContent>
	</xs:complexType>
	
	<!--Zip Code-->
	<xs:complexType name='ct-b380e079-af34-430d-88b4-599087fcdec4'>
		<xs:complexContent>
			<xs:restriction base='mlhim2:ElementType'>
				<xs:sequence>
					<xs:element  maxOccurs='1' minOccurs='1' ref='mlhim2:el-c2e6f182-ea59-491c-a2ec-04c8b6933f42'/>
				</xs:sequence>
			</xs:restriction>
		</xs:complexContent>
	</xs:complexType>
	<xs:element name='el-c2e6f182-ea59-491c-a2ec-04c8b6933f42' substitutionGroup='mlhim2:Element-dv' type='mlhim2:ct-c2e6f182-ea59-491c-a2ec-04c8b6933f42'/>
	
	
	<xs:complexType name='ct-c2e6f182-ea59-491c-a2ec-04c8b6933f42'>
		<xs:complexContent>
			<xs:restriction base='mlhim2:DvStringType'>
				<xs:sequence>
					<xs:element maxOccurs='1' minOccurs='1' name='data-name' type='xs:string' fixed='Zip Code'/>
					<xs:element maxOccurs='1' minOccurs='0' ref='mlhim2:ExceptionalValue'/>
					<xs:element maxOccurs='1' minOccurs='0' name='valid-time-begin' type='xs:dateTime'/>
					<xs:element maxOccurs='1' minOccurs='0' name='valid-time-end' type='xs:dateTime'/>
					<xs:element maxOccurs='1' minOccurs='1' name='DvString-dv' type='xs:string' >
						<xs:annotation>
							<xs:documentation>
								US Zip Code
							</xs:documentation>
						</xs:annotation>
					</xs:element>
				</xs:sequence>
			</xs:restriction>
		</xs:complexContent>
	</xs:complexType>
	
	<!--State-->
	<xs:complexType name='ct-ef538f44-e84b-455e-8db5-2ef40ef40b5e'>
		<xs:complexContent>
			<xs:restriction base='mlhim2:ElementType'>
				<xs:sequence>
					<xs:element  maxOccurs='1' minOccurs='1' ref='mlhim2:el-8e1b9ea1-56e4-4f25-90ae-f0d05a475766'/>
				</xs:sequence>
			</xs:restriction>
		</xs:complexContent>
	</xs:complexType>
	<xs:element name='el-8e1b9ea1-56e4-4f25-90ae-f0d05a475766' substitutionGroup='mlhim2:Element-dv' type='mlhim2:ct-8e1b9ea1-56e4-4f25-90ae-f0d05a475766'/>
	
	
	<xs:complexType name='ct-8e1b9ea1-56e4-4f25-90ae-f0d05a475766'>
		<xs:complexContent>
			<xs:restriction base='mlhim2:DvStringType'>
				<xs:sequence>
					<xs:element maxOccurs='1' minOccurs='1' name='data-name' type='xs:string' fixed='State'/>
					<xs:element maxOccurs='1' minOccurs='0' ref='mlhim2:ExceptionalValue'/>
					<xs:element maxOccurs='1' minOccurs='0' name='valid-time-begin' type='xs:dateTime'/>
					<xs:element maxOccurs='1' minOccurs='0' name='valid-time-end' type='xs:dateTime'/>
					<xs:element maxOccurs='1' minOccurs='1' name='DvString-dv' type='xs:string' >
						<xs:annotation>
							<xs:documentation>
								US State Abbreviation
							</xs:documentation>
						</xs:annotation>
					</xs:element>
				</xs:sequence>
			</xs:restriction>
		</xs:complexContent>
	</xs:complexType>
	
	<!--City Name-->
	<xs:complexType name='ct-0b9a525a-fdc8-40f3-abd8-a83a993d418c'>
		<xs:complexContent>
			<xs:restriction base='mlhim2:ElementType'>
				<xs:sequence>
					<xs:element  maxOccurs='1' minOccurs='1' ref='mlhim2:el-665cf74e-8a0e-4b08-a1e4-58e3e0faf2ec'/>
				</xs:sequence>
			</xs:restriction>
		</xs:complexContent>
	</xs:complexType>
	<xs:element name='el-665cf74e-8a0e-4b08-a1e4-58e3e0faf2ec' substitutionGroup='mlhim2:Element-dv' type='mlhim2:ct-665cf74e-8a0e-4b08-a1e4-58e3e0faf2ec'/>
	
	
	<xs:complexType name='ct-665cf74e-8a0e-4b08-a1e4-58e3e0faf2ec'>
		<xs:complexContent>
			<xs:restriction base='mlhim2:DvStringType'>
				<xs:sequence>
					<xs:element maxOccurs='1' minOccurs='1' name='data-name' type='xs:string' fixed='City Name'/>
					<xs:element maxOccurs='1' minOccurs='0' ref='mlhim2:ExceptionalValue'/>
					<xs:element maxOccurs='1' minOccurs='0' name='valid-time-begin' type='xs:dateTime'/>
					<xs:element maxOccurs='1' minOccurs='0' name='valid-time-end' type='xs:dateTime'/>
					<xs:element maxOccurs='1' minOccurs='1' name='DvString-dv' type='xs:string' >
						<xs:annotation>
							<xs:documentation>
								City name.
							</xs:documentation>
						</xs:annotation>
					</xs:element>
				</xs:sequence>
			</xs:restriction>
		</xs:complexContent>
	</xs:complexType>
	
	<!--Drivers License Number-->
	<xs:complexType name='ct-09952004-eed1-4ba7-be91-340bc24af7c3'>
		<xs:complexContent>
			<xs:restriction base='mlhim2:ElementType'>
				<xs:sequence>
					<xs:element  maxOccurs='1' minOccurs='1' ref='mlhim2:el-1af72a9d-c5dd-4996-b3d9-adbad9c69e55'/>
				</xs:sequence>
			</xs:restriction>
		</xs:complexContent>
	</xs:complexType>
	<xs:element name='el-1af72a9d-c5dd-4996-b3d9-adbad9c69e55' substitutionGroup='mlhim2:Element-dv' type='mlhim2:ct-1af72a9d-c5dd-4996-b3d9-adbad9c69e55'/>
	
	
	<xs:complexType name='ct-1af72a9d-c5dd-4996-b3d9-adbad9c69e55'>
		<xs:complexContent>
			<xs:restriction base='mlhim2:DvStringType'>
				<xs:sequence>
					<xs:element maxOccurs='1' minOccurs='1' name='data-name' type='xs:string' fixed='Drivers License Number'/>
					<xs:element maxOccurs='1' minOccurs='0' ref='mlhim2:ExceptionalValue'/>
					<xs:element maxOccurs='1' minOccurs='0' name='valid-time-begin' type='xs:dateTime'/>
					<xs:element maxOccurs='1' minOccurs='0' name='valid-time-end' type='xs:dateTime'/>
					<xs:element maxOccurs='1' minOccurs='1' name='DvString-dv' type='xs:string' >
						<xs:annotation>
							<xs:documentation>
								Drivers License Number
							</xs:documentation>
						</xs:annotation>
					</xs:element>
				</xs:sequence>
			</xs:restriction>
		</xs:complexContent>
	</xs:complexType>
	
	<!--US SSN-->
	<xs:complexType name='ct-88d991a4-aa08-4767-aaab-fbf4197d5bd7'>
		<xs:complexContent>
			<xs:restriction base='mlhim2:ElementType'>
				<xs:sequence>
					<xs:element  maxOccurs='1' minOccurs='1' ref='mlhim2:el-c9fc43a3-ca79-491e-a788-963562ee3828'/>
				</xs:sequence>
			</xs:restriction>
		</xs:complexContent>
	</xs:complexType>
	<xs:element name='el-c9fc43a3-ca79-491e-a788-963562ee3828' substitutionGroup='mlhim2:Element-dv' type='mlhim2:ct-c9fc43a3-ca79-491e-a788-963562ee3828'/>
	
	
	<xs:complexType name='ct-c9fc43a3-ca79-491e-a788-963562ee3828'>
		<xs:complexContent>
			<xs:restriction base='mlhim2:DvStringType'>
				<xs:sequence>
					<xs:element maxOccurs='1' minOccurs='1' name='data-name' type='xs:string' fixed='US SSN'/>
					<xs:element maxOccurs='1' minOccurs='0' ref='mlhim2:ExceptionalValue'/>
					<xs:element maxOccurs='1' minOccurs='0' name='valid-time-begin' type='xs:dateTime'/>
					<xs:element maxOccurs='1' minOccurs='0' name='valid-time-end' type='xs:dateTime'/>
					<xs:element maxOccurs='1' minOccurs='1' name='DvString-dv' type='xs:string' >
						<xs:annotation>
							<xs:documentation>
								US Social Security Number
							</xs:documentation>
						</xs:annotation>
					</xs:element>
				</xs:sequence>
			</xs:restriction>
		</xs:complexContent>
	</xs:complexType>
	
	<!--Phone Number-->
	<xs:complexType name='ct-018c1d4e-d8e5-4537-b564-45191d5577bd'>
		<xs:complexContent>
			<xs:restriction base='mlhim2:ElementType'>
				<xs:sequence>
					<xs:element  maxOccurs='1' minOccurs='1' ref='mlhim2:el-8f2cc797-5603-46c2-a561-feb4a0bb7dd0'/>
				</xs:sequence>
			</xs:restriction>
		</xs:complexContent>
	</xs:complexType>
	<xs:element name='el-8f2cc797-5603-46c2-a561-feb4a0bb7dd0' substitutionGroup='mlhim2:Element-dv' type='mlhim2:ct-8f2cc797-5603-46c2-a561-feb4a0bb7dd0'/>
	
	
	<xs:complexType name='ct-8f2cc797-5603-46c2-a561-feb4a0bb7dd0'>
		<xs:complexContent>
			<xs:restriction base='mlhim2:DvStringType'>
				<xs:sequence>
					<xs:element maxOccurs='1' minOccurs='1' name='data-name' type='xs:string' fixed='US Phone Number'/>
					<xs:element maxOccurs='1' minOccurs='0' ref='mlhim2:ExceptionalValue'/>
					<xs:element maxOccurs='1' minOccurs='0' name='valid-time-begin' type='xs:dateTime'/>
					<xs:element maxOccurs='1' minOccurs='0' name='valid-time-end' type='xs:dateTime'/>
					<xs:element maxOccurs='1' minOccurs='1' name='DvString-dv' type='xs:string' >
						<xs:annotation>
							<xs:documentation>
								US Phone number.
							</xs:documentation>
						</xs:annotation>
					</xs:element>
				</xs:sequence>
			</xs:restriction>
		</xs:complexContent>
	</xs:complexType>
	
	
	
	<!--Email Address-->
	<xs:complexType name='ct-b291c9b2-f0ec-4ec2-9bed-5fac28afbd32'>
		<xs:complexContent>
			<xs:restriction base='mlhim2:ElementType'>
				<xs:sequence>
					<xs:element  maxOccurs='1' minOccurs='1' ref='mlhim2:el-1707ec28-169a-43da-92bf-83eef071255f'/>
				</xs:sequence>
			</xs:restriction>
		</xs:complexContent>
	</xs:complexType>
	<xs:element name='el-1707ec28-169a-43da-92bf-83eef071255f' substitutionGroup='mlhim2:Element-dv' type='mlhim2:ct-1707ec28-169a-43da-92bf-83eef071255f'/>
	
	
	<xs:complexType name='ct-1707ec28-169a-43da-92bf-83eef071255f'>
		<xs:complexContent>
			<xs:restriction base='mlhim2:DvStringType'>
				<xs:sequence>
					<xs:element maxOccurs='1' minOccurs='1' name='data-name' type='xs:string' fixed='Email Address'/>
					<xs:element maxOccurs='1' minOccurs='0' ref='mlhim2:ExceptionalValue'/>
					<xs:element maxOccurs='1' minOccurs='1' name='valid-time-begin' type='xs:dateTime'/>
					<xs:element maxOccurs='1' minOccurs='0' name='valid-time-end' type='xs:dateTime'/>
					<xs:element maxOccurs='1' minOccurs='1' name='DvString-dv' type='xs:string' >
						<xs:annotation>
							<xs:documentation>
								Email Address
							</xs:documentation>
						</xs:annotation>
					</xs:element>
				</xs:sequence>
			</xs:restriction>
		</xs:complexContent>
	</xs:complexType>
	


	<!--First Name-->
	<xs:complexType name='ct-a35f0879-4338-4908-a36f-ce16fc67cf7a'>
		<xs:complexContent>
			<xs:restriction base='mlhim2:ElementType'>
				<xs:sequence>
					<xs:element  maxOccurs='1' minOccurs='1' ref='mlhim2:el-0dc49ca0-94d7-46c9-b7a1-6c2b3b167f16'/>
				</xs:sequence>
			</xs:restriction>
		</xs:complexContent>
	</xs:complexType>
	<xs:element name='el-0dc49ca0-94d7-46c9-b7a1-6c2b3b167f16' substitutionGroup='mlhim2:Element-dv' type='mlhim2:ct-0dc49ca0-94d7-46c9-b7a1-6c2b3b167f16'/>
	
	
	<xs:complexType name='ct-0dc49ca0-94d7-46c9-b7a1-6c2b3b167f16'>
		<xs:complexContent>
			<xs:restriction base='mlhim2:DvStringType'>
				<xs:sequence>
					<xs:element maxOccurs='1' minOccurs='1' name='data-name' type='xs:string' fixed='First Name'/>
					<xs:element maxOccurs='1' minOccurs='0' ref='mlhim2:ExceptionalValue'/>
					<xs:element maxOccurs='1' minOccurs='0' name='valid-time-begin' type='xs:dateTime'/>
					<xs:element maxOccurs='1' minOccurs='0' name='valid-time-end' type='xs:dateTime'/>
					<xs:element maxOccurs='1' minOccurs='1' name='DvString-dv' type='xs:string' >
						<xs:annotation>
							<xs:documentation>
								First name of person.
							</xs:documentation>
						</xs:annotation>
					</xs:element>
				</xs:sequence>
			</xs:restriction>
		</xs:complexContent>
	</xs:complexType>
	
	
	<!--Last Name-->
	<xs:complexType name='ct-7562af32-6e33-4a21-ab84-e9067331c465'>
		<xs:complexContent>
			<xs:restriction base='mlhim2:ElementType'>
				<xs:sequence>
					<xs:element  maxOccurs='1' minOccurs='1' ref='mlhim2:el-c3ba50ac-0370-4755-a138-94bba17691f9'/>
				</xs:sequence>
			</xs:restriction>
		</xs:complexContent>
	</xs:complexType>
	<xs:element name='el-c3ba50ac-0370-4755-a138-94bba17691f9' substitutionGroup='mlhim2:Element-dv' type='mlhim2:ct-c3ba50ac-0370-4755-a138-94bba17691f9'/>
	
	
	<xs:complexType name='ct-c3ba50ac-0370-4755-a138-94bba17691f9'>
		<xs:complexContent>
			<xs:restriction base='mlhim2:DvStringType'>
				<xs:sequence>
					<xs:element maxOccurs='1' minOccurs='1' name='data-name' type='xs:string' fixed='Last Name'/>
					<xs:element maxOccurs='1' minOccurs='0' ref='mlhim2:ExceptionalValue'/>
					<xs:element maxOccurs='1' minOccurs='0' name='valid-time-begin' type='xs:dateTime'/>
					<xs:element maxOccurs='1' minOccurs='0' name='valid-time-end' type='xs:dateTime'/>
					<xs:element maxOccurs='1' minOccurs='1' name='DvString-dv' type='xs:string' >
						<xs:annotation>
							<xs:documentation>
								Last name of person.
							</xs:documentation>
						</xs:annotation>
					</xs:element>
				</xs:sequence>
			</xs:restriction>
		</xs:complexContent>
	</xs:complexType>
	



</xs:schema>

=== anddrenunes/SemanticMedWeb/data/smw/demog/pr-0000000050/demographics.xml
<?xml version="1.0" encoding="UTF-8"?>
<mlhim2:ccd-ca92a9c1-275f-42ca-b1a0-ac0a20cb2ec9 xmlns:mlhim2="http://www.mlhim.org/xmlns/mlhim2/2_4_1" xmlns:data-view="http://www.w3.org/2003/g/data-view#" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.mlhim.org/xmlns/mlhim2/2_4_1 http://www.hkcr.net/ccd/ccd-ca92a9c1-275f-42ca-b1a0-ac0a20cb2ec9.xsd">
    <mlhim2:el-249daa52-7cdc-44bb-8cd8-7071993de08b>
        <mlhim2:cluster-subject>Demographics Cluster</mlhim2:cluster-subject>
        <mlhim2:el-a2bc25db-3111-4cd5-9825-d9c448cdd1a5>
            <mlhim2:el-7562af32-6e33-4a21-ab84-e9067331c465>
                <mlhim2:el-c3ba50ac-0370-4755-a138-94bba17691f9>
                    <mlhim2:data-name>Last Name</mlhim2:data-name>
                    <mlhim2:DvString-dv>Hess</mlhim2:DvString-dv>
                </mlhim2:el-c3ba50ac-0370-4755-a138-94bba17691f9>
            </mlhim2:el-7562af32-6e33-4a21-ab84-e9067331c465>
            <mlhim2:el-a35f0879-4338-4908-a36f-ce16fc67cf7a>
                <mlhim2:el-0dc49ca0-94d7-46c9-b7a1-6c2b3b167f16>
                    <mlhim2:data-name>First Name</mlhim2:data-name>
                    <mlhim2:DvString-dv>Tifany</mlhim2:DvString-dv>
                </mlhim2:el-0dc49ca0-94d7-46c9-b7a1-6c2b3b167f16>
            </mlhim2:el-a35f0879-4338-4908-a36f-ce16fc67cf7a>
            <mlhim2:el-b291c9b2-f0ec-4ec2-9bed-5fac28afbd32>
                <mlhim2:el-1707ec28-169a-43da-92bf-83eef071255f>
                    <mlhim2:data-name>Email Address</mlhim2:data-name>
                    <mlhim2:valid-time-begin>2008-11-05T02:36:28Z</mlhim2:valid-time-begin>
                    <mlhim2:DvString-dv>Tifany.Hess@mlhim-test.org</mlhim2:DvString-dv>
                </mlhim2:el-1707ec28-169a-43da-92bf-83eef071255f>
            </mlhim2:el-b291c9b2-f0ec-4ec2-9bed-5fac28afbd32>
            <mlhim2:el-018c1d4e-d8e5-4537-b564-45191d5577bd>
                <mlhim2:el-8f2cc797-5603-46c2-a561-feb4a0bb7dd0>
                    <mlhim2:data-name>US Phone Number</mlhim2:data-name>
                    <mlhim2:DvString-dv>(995)625-1095</mlhim2:DvString-dv>
                </mlhim2:el-8f2cc797-5603-46c2-a561-feb4a0bb7dd0>
            </mlhim2:el-018c1d4e-d8e5-4537-b564-45191d5577bd>
            <mlhim2:el-88d991a4-aa08-4767-aaab-fbf4197d5bd7>
                <mlhim2:el-c9fc43a3-ca79-491e-a788-963562ee3828>
                    <mlhim2:data-name>US SSN</mlhim2:data-name>
                    <mlhim2:DvString-dv>298-51-4680</mlhim2:DvString-dv>
                </mlhim2:el-c9fc43a3-ca79-491e-a788-963562ee3828>
            </mlhim2:el-88d991a4-aa08-4767-aaab-fbf4197d5bd7>
            <mlhim2:el-09952004-eed1-4ba7-be91-340bc24af7c3>
                <mlhim2:el-1af72a9d-c5dd-4996-b3d9-adbad9c69e55>
                    <mlhim2:data-name>Drivers License Number</mlhim2:data-name>
                    <mlhim2:DvString-dv>H-554-4605-211-AR</mlhim2:DvString-dv>
                </mlhim2:el-1af72a9d-c5dd-4996-b3d9-adbad9c69e55>
            </mlhim2:el-09952004-eed1-4ba7-be91-340bc24af7c3>
            <mlhim2:el-0b9a525a-fdc8-40f3-abd8-a83a993d418c>
                <mlhim2:el-665cf74e-8a0e-4b08-a1e4-58e3e0faf2ec>
                    <mlhim2:data-name>City Name</mlhim2:data-name>
                    <mlhim2:DvString-dv>West Memphis</mlhim2:DvString-dv>
                </mlhim2:el-665cf74e-8a0e-4b08-a1e4-58e3e0faf2ec>
            </mlhim2:el-0b9a525a-fdc8-40f3-abd8-a83a993d418c>
            <mlhim2:el-ef538f44-e84b-455e-8db5-2ef40ef40b5e>
                <mlhim2:el-8e1b9ea1-56e4-4f25-90ae-f0d05a475766>
                    <mlhim2:data-name>State</mlhim2:data-name>
                    <mlhim2:DvString-dv>AR</mlhim2:DvString-dv>
                </mlhim2:el-8e1b9ea1-56e4-4f25-90ae-f0d05a475766>
            </mlhim2:el-ef538f44-e84b-455e-8db5-2ef40ef40b5e>
            <mlhim2:el-b380e079-af34-430d-88b4-599087fcdec4>
                <mlhim2:el-c2e6f182-ea59-491c-a2ec-04c8b6933f42>
                    <mlhim2:data-name>Zip Code</mlhim2:data-name>
                    <mlhim2:DvString-dv>72301</mlhim2:DvString-dv>
                </mlhim2:el-c2e6f182-ea59-491c-a2ec-04c8b6933f42>
            </mlhim2:el-b380e079-af34-430d-88b4-599087fcdec4>
            <mlhim2:el-06b0c425-f7ef-4d46-8573-97091ae52d60>
                <mlhim2:el-0ac3f22e-64ca-4309-be88-874cd14649a0>
                    <mlhim2:data-name>Gender</mlhim2:data-name>
                    <mlhim2:DvString-dv>Male</mlhim2:DvString-dv>
                </mlhim2:el-0ac3f22e-64ca-4309-be88-874cd14649a0>
            </mlhim2:el-06b0c425-f7ef-4d46-8573-97091ae52d60>
        </mlhim2:el-a2bc25db-3111-4cd5-9825-d9c448cdd1a5>
    </mlhim2:el-249daa52-7cdc-44bb-8cd8-7071993de08b>
</mlhim2:ccd-ca92a9c1-275f-42ca-b1a0-ac0a20cb2ec9>
